### ISSUE TITLE
Scatter plot doesn't run whilst in qsub

### ISSUE THREAD

**Issue by nelse003** [nelse003/exhaustive_search#6]
When running Repeat_exhaustive_search.py in qsub:

```
#!/bin/bash

export XChemExplorer_DIR="/dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer"
source /dls/science/groups/i04-1/software/XChemExplorer_new/XChemExplorer/setup-scripts/pandda.setup-sh

cd /dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search
```
Scatterplot function does not work. 

Error:

$CCP4/bin/ccp4-python /dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search/Repeating_exhaustive_search.py input.database_path="/dls/labxchem/data/2016/lb13385-64/processing/analysis_xce2_june_17/database/soakDBDataFile_july.sqlite"

Traceback (most recent call last):
  File "/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search/Repeating_exhaustive_search.py", line 180, in <module>
    run_default(run=run, master_phil=master_phil, args=sys.argv[1:], blank_arg_prepend=blank_arg_prepend)
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/panddas-0.2.12_dev-py2.7.egg/giant/jiffies/__init__.py", line 16, in __init__
    out = run(params=working_phil.extract())
  File "/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search/Repeating_exhaustive_search.py", line 150, in run
    scatter_plot(params.input.csv_name)
  File "/dls/science/groups/i04-1/elliot-dev/Work/exhaustive_search/plot_exhaustive_search.py", line 22, in scatter_plot
    fig = plt.figure()
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 47, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 54, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 72, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

**Comment by nelse003** [comment]
Generate images without having a window appear

The easiest way to do this is use a non-interactive backend (see What is a backend?) such as Agg (for PNGs), PDF, SVG or PS. In your figure-generating script, just call the matplotlib.use() directive before importing pylab or pyplot:

import matplotlib
matplotlib.use('Agg')
